### ISSUE TITLE
Update Docusaurus to v2

### ISSUE THREAD

**Issue by ybiquitous** [sider/sider-docs#307]
https://v2.docusaurus.io/

Docusaurus v2 is faster than v1 and has so many features! See <https://docusaurus.io/docs/migration>.

v2 is alpha yet, but Redux [migrated to v2](https://github.com/reduxjs/redux/pull/3635).

**Comment by ybiquitous** [comment]
Finally, it reaches beta!
https://docusaurus.io/blog/2021/05/12/announcing-docusaurus-two-beta

**Comment by ybiquitous** [comment]
We need to contact the DocSearch team to update our search indexes ([`configs/sider.json`](https://github.com/algolia/docsearch-configs/blob/93d6e217d54ff31d19ae2c601d062e830350a44a/configs/sider.json)) after deploying the new doc site.

https://docusaurus.io/docs/migration/manual#algolia

**Comment by ybiquitous** [comment]
> You can contact the DocSearch team (@shortcuts, @s-pace) for support. They can update it for you and trigger a recrawl of your site to restore the search (otherwise you will have to wait up to 24h for the next scheduled crawl)

The search index will be updated in 24 hours.

All done! 🙌🏼

**Comment by shortcuts** [comment]
Hey there, you can update your config by adding/replacing [all of these options from the docusaurus v2 config template](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json#L11-L43) and then open a pull request on [this repository](https://github.com/algolia/docsearch-configs/), I'll make sure to review it :)

**Comment by ybiquitous** [comment]
@shortcuts Oh, thank you for the feedback! I'll create a PR soon. 💪🏼
