### ISSUE TITLE
Remove "Description" column in options table

### ISSUE THREAD

**Issue by ybiquitous** [sider/sider-docs#358]
I'm wondering whether the "Description" column is really needed in each tool's options table. 🤔 

https://help.sider.review/tools/javascript/eslint#configuration-via-sideryml

<img width="756" alt="image" src="https://user-images.githubusercontent.com/473530/79422944-bbf16d80-7ff8-11ea-9cf4-4087485c9682.png">

The reasons:

- Too much information in a table.
- We have an internal link to each option.
- Description in an options table is duplicated with its option's detailed description.

**Comment by yykamei** [comment]
I agree with you.

**Comment by ybiquitous** [comment]
Thanks for the feedback. I've changed the title to clarify the issue's purpose.

**Comment by ybiquitous** [comment]
All done. 🎉
