### ISSUE TITLE
Replace `sider/ecr-image-puller` image with AWS CLI sample code

### ISSUE THREAD

**Issue by ybiquitous** [sider/sider-docs#598]
We will not manage the [`sider/ecr-image-puller`](https://hub.docker.com/r/sider/ecr-image-puller) and remove it in the future.

So, we need to rewrite the following section:

https://help.sider.review/enterprise/installation#get-docker-image

- Add a link to the AWS CLI official document.
- Replace the sample code with one using AWS CLI directly.

**Comment by gnakagaw** [comment]
Should be addressed with https://github.com/sider/sideci/issues/11219
