### ISSUE TITLE
Documents for metrics and inspections

### ISSUE THREAD

**Issue by suetsuguk** [sider/sider-docs#613]
Documents for metrics are missing from the Sider Documentation.
Sider provides three analyzers to compute software metrics. But a combined single page will be convenient for readers rather than multiple pages for individual metrics runners.

Note:
Document links of the metrics runners in [this list](https://github.com/sider/runners#supported-analyzers) are broken. Need to change them to proper links when the pages are created.

**Comment by ybiquitous** [comment]
> Document links of the metrics runners in [this list](https://github.com/sider/runners#supported-analyzers) are broken.

I’ve fixed the broken list. We need to update `doc: ""` in `analyzers.yml`:

https://github.com/sider/runners/blob/b18bfb42d7789823a617e69d8db9a54c8219f3ac/analyzers.yml#L105

**Comment by suetsuguk** [comment]
Also, there is no document about the inspections. We need to address it at the same time.

**Comment by suetsuguk** [comment]
Aki commented about metrics.

```
[Aki] 一番複雑なのは、inspections_controller.rb　とのことですが、そんなに複雑に見えないのと、一方で、複雑度0 になっているCharts.tsx　は、中身をみると結構ネスト深いです。ネストは深いが、if, for, while などの制御文で深くなっているわけではないから、複雑度は低くでてしまうんですかね？
[Ken] tsxには対応していないので0となります。複雑度はそのファイル内の関数ごとの複雑度の合計なのでネストが浅くても合計するとその数字になります。
[Aki] "Clones" の見方なのですが、これは同一ファイル内のコピペのみをカウントしているんでしょうか？
[Ken] Clonesは密度をプロットしていて「重複した行/そのファイル行数」です。重複は「他のファイルの一部との重複」および「自分自身の一部との重複」のどちらもカウントしている。
```
